######################
# General settings
######################
local_dir: /home/mike-loomans/git/extras/virshimeome/cwd/
virshimeome_dir: /home/mike-loomans/git/extras/virshimeome/cwd/virshimeome

download_memory: 8
download_threads: 2
