######################
## General settings ##
######################
# Dirs
PROJECT: test_main
virshimeome_dir: /projects/arumugam/people/mnc390/virome_pipelines/virshimeome
contig_dir: /projects/arumugam/scratch/mjq180/Diet3_for_Mike 
output_dir: /projects/arumugam/scratch/mnc390/virome_testing/no_filter_virshimeome_pipeline_output
deep_vir_finder_dir: /projects/arumugam/people/mnc390/virome_pipelines/virshimeome/DeepVirFinder

#####################
##  Tool settings  ##
#####################
# Contig selection (custom script & virsorter2)
circular: circular
max_contig_length: 500000
min_contig_length: 2000
min_score_vir_recognition: 0.5

# DVF
min_score_dvf: 0.7
max_pval_dvf: 0.05

# Read to contig alignment (BWA)
algorithm_bwa: mem
# Add more options for bwa mapping after the program as a whole is working. 

# phabox
prophage_reject: 0.2

# ANI
ani_threshold: 99.9 # Percentage not decimal