######################
## General settings ##
######################
# Dirs
PROJECT: mike_test
virshimeome_dir: /home/mike-loomans/git/extras/virshimeome/
contig_dir: /home/mike-loomans/git/extras/virshimeome/cwd/data/
output_dir: /home/mike-loomans/git/extras/virshimeome/cwd/output/
deep_vir_finder_dir: /home/mike-loomans/git/extras/virshimeome/cwd/DeepVirFinder/

#####################
##  Tool settings  ##
#####################
# Contig selection (custom script & virsorter2)
circular: circular
max_contig_length: 500000
min_contig_length: 2000
min_score_vir_recognition: 0.5

# DVF
min_score_dvf: 0.7
max_pval_dvf: 0.05

# phabox
prophage_reject: 0.2

# ANI
ani_threshold: 99.9 # Percentage not decimal