######################
## General settings ##
######################

PROJECT: test_case_vs2
working_dir: /projects/arumugam/people/mnc390/virome_pipelines/virshimome/test
local_dir: /projects/arumugam/people/mnc390/virome_pipelines/virshimome/test
virshimeome_dir: /projects/arumugam/people/mnc390/virome_pipelines/virshimome
hq_reads_dir: /projects/arumugam/people/mnc390/virome_pipelines/virshimome/test/reads
contig_dir: /projects/arumugam/people/mnc390/virome_pipelines/virshimome/test/MAGS
output_dir: /projects/arumugam/scratch/mnc390/virome_testing/vs2_output
threads: 8
memory: 20 # In gigabytes

#####################
##  Tool settings  ##
#####################
max_contig_length: 500000
min_contig_length: 1500
min_score_vir_recognition: 0.5
algorithm_bwa: mem
cores: 4
min_length_alignment_abundance: 80
percentage_identity_abundance: 95 # Percentage not decimal
percentage_read_aligned_abundance: 80 # Percentage not decimal
